In [1]:
import numpy as np

In [3]:
train_data = np.array([[0,0,-1], [0,1,-1], [1,0,-1], [1,1,1]])

In [8]:
train_data

array([[ 0,  0, -1],
       [ 0,  1, -1],
       [ 1,  0, -1],
       [ 1,  1,  1]])

In [32]:
train_x = train_data[:,:2]
train_x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [33]:
train_y = train_data[:,2:]
train_y

array([[-1],
       [-1],
       [-1],
       [ 1]])

In [63]:
ones = np.ones([len(train_x), 1])
ones

array([[1.],
       [1.],
       [1.],
       [1.]])

In [64]:
np.append(ones, train_x, axis=1)

array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [96]:
update_train_x = np.append(ones, train_x, axis=1)
update_train_x

array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [162]:
w = np.zeros([len(train_x[0]) + 1], dtype=float)
w

array([0., 0., 0.])

In [163]:
print(w)
for epocs in range(100000):
    is_changed = False
    for i in range(len(train_y)):
        y_predict = np.matmul(w, update_train_x[i])
        if y_predict < 0 and train_y[i] > 0:
            w = np.add(w, np.transpose(update_train_x[i]))
            is_changed = True
        elif y_predict >= 0 and train_y[i] < 0:
            w = np.subtract(w, np.transpose(update_train_x[i]))
            is_changed = True
    
    print(np.transpose(w))
    if not is_changed:
        break

[0. 0. 0.]
[0. 1. 1.]
[-1.  2.  1.]
[-2.  2.  1.]
[-2.  2.  2.]
[-3.  2.  1.]
[-3.  2.  1.]
